### PR TITLE
Bumps to latest zipkin and hints about JAVA_OPTS in docker

### PR DESCRIPTION
**Pull request by adriancole**

### CODE REVIEW

**Comment by adriancole** [comment]
pending maven central sync (which might be done by now)

**Comment by marcingrzejszczak** [comment]
Hmm Travis seems to start dying at some point of the build. I guess we might be running out of memory or sth.

**Comment by adriancole** [comment]
kicked. in zipkin, we have a heartbeat shell script to stop travis from
killing things that are progressing.

**Comment by marcingrzejszczak** [comment]
It ran out of memory ;) 

```
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000008b000000, 82837504, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 82837504 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/travis/build/spring-cloud/spring-cloud-sleuth/target/brewery/hs_err_pid6754.log
```

**Comment by adriancole** [comment]
christmas build!

**Comment by dsyer** [comment]
LGTM

**Pull request merged**
