### PR TITLE
Fix for inability to provide custom implementation of AsyncClientHttp…

### PR DESCRIPTION
**Pull request by premanandc**
The problem happens only when providing a custom implementation of the AsyncClientHttpAsyncClientHttpRequestFactory.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@premanandc Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=342)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=342) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@premanandc Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=342)!

**Comment by premanandc** [comment]
These tests fail on master as well without my changes.

**Comment by marcingrzejszczak** [comment]
Actually some other tests fail too so don't worry about this

**Comment by premanandc** [comment]
You're still awake? Wow! Yes, I think we've got errors because of changes in some of our upstream snapshot dependencies.

**Comment by marcingrzejszczak** [comment]
I never sleep ;) Sth's change with Feign that's why a lot of stuff is failing

**Comment by premanandc** [comment]
:) Yes, it looks like it. FWIW, the tests did pass locally. Now they're failing. Hope the PR is useful.

**Comment by marcingrzejszczak** [comment]
Of course it's useful! Thanks a lot for the contribution! I'll try to apply this to 1.0.x branch first

**Comment by marcingrzejszczak** [comment]
Great job! Thanks a lot for your contribution!!

**Pull request merged**
