### PR TITLE
Hacks standard span names in, but redundantly parsing

### PR DESCRIPTION
**Pull request by adriancole**
This has no tests, and needs to be done similarly for flux. feel free to close this with a different PR or commit. The approach is redundantly parsing at the mvc layer even when servlet closes the span.

This is kindof ok for now I think, as we have other work in brave needed to make the practice more standard (because we might try to avoid redundant parsing for the small overhead it makes.. not sure it will be possible)

Once this is in, things look pretty by default. ex building then using snapshot on https://github.com/openzipkin/sleuth-webmvc-example Once something like this is together, I'd recommend cutting a milestone as pretty spans are better than "get", "get", "get"

screen shot 2018-03-04 at 10 47 52 am

BTW, this is https://github.com/spring-cloud/spring-cloud-sleuth/issues/802, however it doesn't add the http.route tag by default, rather just uses it for the span name. I think micrometer's tag policy is mildly different at least in case format anyway, but anyway span names are a great start

### CODE REVIEW

**Comment by adriancole** [comment]
actually I think I have a more sustainable alternative:

All things layered on servlet add the request attribute "http.route" some time before a response completes. If the servlet closes the span, it can find and parse this. If something else closes the span, they use however they like.

**Comment by adriancole** [comment]
we can do something like what's in this change temporarily until https://github.com/openzipkin/brave/pull/635 or we can merge that and rebase this.

**Comment by marcingrzejszczak** [comment]
I guess that's made obsolete via https://github.com/spring-cloud/spring-cloud-sleuth/pull/878 ?

**Comment by marcingrzejszczak** [comment]
I'd go with merging https://github.com/openzipkin/brave/pull/635 and updating Brave in Sleuth

**Comment by adriancole** [comment]
yeah the other approach is better

**Pull request closed without merging**
