### PR TITLE
Ignore legacy keys in MDC.

### PR DESCRIPTION
**Pull request by bjartek**
Added a new property disableLegacyKeys to SLF4jProperties. If that property is set ignore the legacy keys in MDC

### CODE REVIEW

**Comment by bjartek** [comment]
Not really sure why that test failed. I did not touch any codepath there I think.

**Comment by marcingrzejszczak** [comment]
Actually, for master we can remove those keys whatsover. Are you willing to change this PR to remove instead of ignoring legacy keys?

**Comment by bjartek** [comment]
Sure I can fix that!

**Comment by bjartek** [comment]
Was this what you had in mind or did i misunderstand the task?

**Comment by marcingrzejszczak** [comment]
Yes! Thanks a lot

**Comment by adriancole** [comment]
Added to https://github.com/spring-cloud/spring-cloud-sleuth/wiki/Spring-Cloud-Sleuth-3.0-Migration-Guide

**Pull request merged**
