### PR TITLE
Thermoweb bugfix/2246 handle invocation target exception

### LINKED ISSUE #2246: TraceSessionRepositoryAspect#callMethodOnWrappedObject does not handle InvocationTargetException
**Describe the bug**
I am using spring-cloud-sleuth-instrumentation-3.1.5.jar in combination with spring-aop-5.3.24.jar

The method `callMethodOnWrappedObject(ProceedingJoinPoint pjp, T target)` invokes a method to access a sessionRepository.
But it doesn't handle the case properly, when the invoked method throws a `RuntimeException` or another declared Exception.

The result of this bug is, that a `org.springframework.web.reactive.handler.WebFluxResponseStatusExceptionHandler` and perhaps other places also see a `java.lang.reflect.UndeclaredThrowableException` instead of the actually thrown exception.
The `UndeclaredThrowableException` is created in https://github.com/spring-projects/spring-framework/blob/46875c91ced9387a598c3ca7eba3ed23fdb4fc63/spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java#L769
because the called sessionRepository method doesn't declare to throw an `InvocationTargetException` (which is correct).

Current implementation: https://github.com/spring-cloud/spring-cloud-sleuth/blob/8302481d89fc6744876ba560f95aab604c7890f6/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/session/TraceSessionRepositoryAspect.java#L82

Suggested implementation:
```java
try {
  return method.invoke(target, pjp.getArgs());
} catch(InvocationTargetException ex) {
  throw ex.getCause();
}
```
similar to https://github.com/spring-projects/spring-framework/blob/46875c91ced9387a598c3ca7eba3ed23fdb4fc63/spring-aop/src/main/java/org/springframework/aop/aspectj/AbstractAspectJAdvice.java#L640
or you use org.springframework.util.ReflectionUtils.invokeMethod.

I found a similar issue [#1092](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1092). Maybe there are more like this.

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
fixes gh-2246

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Congrats @thermoweb  on your first contribution! :tada:

**Comment by thermoweb** [comment]
> Congrats @thermoweb on your first contribution! tada

Thanks, you did all the work at the end ^^'

**Comment by marcingrzejszczak** [comment]
We did it together @thermoweb ! :)

**Comment by ghost** [comment]
Thank you both. Nice and clean code.

**Pull request merged**
