### PR TITLE
add /messaging annotations

### PR DESCRIPTION
**Pull request by spencergibb**
Created using https://github.com/scratches/voter-counter

Could ignore tracing headers.

@dsyer @adriancole @mstine @b

screenshotsleuthmessaging

### CODE REVIEW

**Comment by dsyer** [comment]
Yeah, need to ignore the tracing headers.

**Comment by spencergibb** [comment]
tracing headers ignored.

**Comment by dsyer** [comment]
That's a start. We could say something about the payload (type, size if known, e.g. if it's a String or byte[])? ANy other ideas @garyrussell, @markfisher ?

**Comment by adriancole** [comment]
I like the namespacing

Food for thought: we will eventually need to think about the size of this data. Going from binary data with integer keys (thrift or protobuf) to uncompressed json with lengthy key names is probably an order of magnitude more data. Add to this that the biggest data issue in observability at Twitter is most was never read. Should we be auto attaching things like accept or content header values? Would this help in latency analysis?

**Comment by spencergibb** [comment]
maybe there can be some kind of opt-in or opt-out and CF could be opinionated on what that is.

**Comment by spencergibb** [comment]
Closed via 0f76427ebf48b2f0838aa725c882c101e821f543

**Pull request closed without merging**
