### PR TITLE
Fix incorrect comparison for sampling always

### PR DESCRIPTION
**Pull request by cbuehler**
`percentage`is a `float`, where 1.0f means 100%

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cbuehler Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=515)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=515) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by marcingrzejszczak** [comment]
Can you please write some tests to show what you are trying to achieve? Thanks :)

**Comment by pivotal-issuemaster** [comment]
@cbuehler Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=515)!

**Comment by marcingrzejszczak** [comment]
ping @cbuehler ?

**Comment by marcingrzejszczak** [comment]
Closing due to inactivity

**Pull request closed without merging**
