### PR TITLE
Kafka instrumentation

### PR DESCRIPTION
**Pull request by flavium31**
Raised this PR as suggested by @marcingrzejszczak in #1906

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Congrats @flavium31 !

**Comment by marcingrzejszczak** [comment]
BTW have you added the docs? Cause I don't see it. Please file it in another PR then

**Comment by marcingrzejszczak** [comment]
Argh I haven't noticed that all of your `since` are from `3.0.3` - we need to fix it with `3.1.0`

**Comment by flavium31** [comment]
@marcingrzejszczak thanks for feedback, we will raise another PR with the requested changes. If it sounds good to you, I can also include an autoconfiguration module in that PR (which I realized we're still missing here) along with some more integration tests to cover all decorated Kafka clients (Consumer, Producer, Receiver and Sender)

**Comment by marcingrzejszczak** [comment]
Great!

**Pull request merged**
