### PR TITLE
Adds support for customize HandlerParser postHandle

### PR DESCRIPTION
**Pull request by wuwen5**
Spring MVC customize traced requests handler add postHandle method.

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Hi! Thanks for the pr. Can you elaborate on why we need this change and what problem are you trying to solve?

**Comment by wuwen5** [comment]
It is convenient to customize tag information, such as httpstatus, payload, etc

In the case of use ```org.springframework.web.filter.AbstractRequestLoggingFilter```, the ```payload``` value can only be obtained through ```posthandler```, but not by ```prehandler```

```java

@Bean
HandlerParser handlerParser() {
    return new HandlerParser() {

        protected void postHandle(HttpServletRequest request, Object handler, ModelAndView modelAndView,
                                  SpanCustomizer customizer) {

            customizer.tag("http.status.code", modelAndView.getStatus().value());

            customizer.tag("http.payload", getMessagePayload(request));
            //etc...
        }

        protected String getMessagePayload(HttpServletRequest request) {
            ContentCachingRequestWrapper wrapper =
                    WebUtils.getNativeRequest(request, ContentCachingRequestWrapper.class);
            if (wrapper != null) {
                byte[] buf = wrapper.getContentAsByteArray();
                if (buf.length > 0) {
                    int length = Math.min(buf.length, getMaxPayloadLength());
                    try {
                        return new String(buf, 0, length, wrapper.getCharacterEncoding());
                    }
                    catch (UnsupportedEncodingException ex) {
                        return "[unknown]";
                    }
                }
            }
            return null;
        }
    };
}
```

**Comment by marcingrzejszczak** [comment]
I see. Can you write a test  for this feature? Also since it's a new feature can you apply the pr to the 3.1.x branch?

**Comment by marcingrzejszczak** [comment]
Thanks for changing the branch. Can you write a test for this please?

**Pull request merged**
