### PR TITLE
Route build on both container and Trusty infrastructures

### PR DESCRIPTION
**Pull request by cotsog**
Can you try this out?

I'm curious to see if it's rather the way MAVEN_OPTS are specified that makes a difference or the infrastructure.

Thanks!

### CODE REVIEW

**Comment by spencergibb** [comment]
Why? what are you trying to fix?

**Comment by cotsog** [comment]
Hi @spencergibb,

I'm a Customer Support Engineer at Travis CI and I'm investigating a build failure that @marcingrzejszczak reported.

**Comment by spencergibb** [comment]
Thanks for the clarification. I'll let @marcingrzejszczak take care of it then.

**Comment by dsyer** [comment]
We gave up on docker in travis (and everywhere in fact), so this is now redundant I believe.

**Pull request closed without merging**
