### PR TITLE
Use ThreadLocal.remove() rather than .set(null)

### PR DESCRIPTION
**Pull request by spencergibb**
fixes gh-27

/cc @rwinch

### CODE REVIEW

**Comment by rwinch** [comment]
Looks good to me :)

**Comment by cincat** [comment]
@rwinch @spencergibb I think the memory leaks is not caused by ThreadLocal.set(null), because Thread just hold the weak reference of ThreadLocal variable, the strong relationship held is by the thread itself.

**Comment by marcingrzejszczak** [comment]
You're referring to the code that is 6 years old. There's no such code anymore!

**Comment by cincat** [comment]
It's okay, I just wanna to confirm that ThreadLocal.set(null) cannot cause memory leaks.

**Comment by cincat** [comment]
And I am certain that the code is never changed since 6 years ago.

**Comment by spencergibb** [comment]
@cincat there's no such class `TraceContextHolder` anymore.

**Pull request merged**
