### PR TITLE
Updates to Zipkin 1.7

### PR DESCRIPTION
**Pull request by adriancole**
Notably includes CORS config and version in the /info endpoint.

https://github.com/openzipkin/zipkin/releases/tag/1.7.0

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Should we update also - https://github.com/spring-cloud-samples/brewery/blob/master/zipkin-server/build.gradle#L13 ?

**Comment by marcingrzejszczak** [comment]
Do we want to have it also for 1.0.x ?

**Comment by adriancole** [comment]
ya for good measure we should

**Comment by adriancole** [comment]
sure!

**Comment by adriancole** [comment]
well, this is spring-boot 1.4, so as long as 1.0.x is ok with that

**Comment by marcingrzejszczak** [comment]
Ah 1.0.x doesn't like boot 1.4 - so let's skip it

**Pull request merged**
