### PR TITLE
wip: Intercept Spring Data Repositories

### PR DESCRIPTION
**Pull request by embs**
Intercept Spring Data Repositories methods calls to instrument database calls.

Related to #788

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@embs Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=790)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=790) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by adriancole** [comment]
probably better to hold off on creating PRs next time, at least until more discussion occurs. There's a lot of code in sleuth and we need to make sure we merge things that multiple folks buy into. For example, working in your own repo first is a nice way to start.

**Comment by marcingrzejszczak** [comment]
I agree with Adrian. I'll close this PR for now.

**Comment by embs** [comment]
I was expecting to gather some feedback and discussing implementation questions through this PR. But I'll try to extract it to an external library.

Thank you both for your help. :)

**Comment by adriancole** [comment]
feel free to copy us on PRs in your repo (I often comment on others' repos, too)

**Pull request closed without merging**
