### PR TITLE
Add instrumenting for jms

### PR DESCRIPTION
**Pull request by Stefku**
Fixes gh-695

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
I closed the PR against `1.2.x`. 

Will this functionality even work? I mean it creates a new span each time a `@JmsListener` method is called. But you're not retrieving any tracing information from the message itself. What if I received a message that already contains span information?

Also I don't think we want an explicit dependency on `activemq`. `Activemq` can be there in the tests but we'd need something more generic in optional compile scope.

**Comment by Stefku** [comment]
Thanks for the review.

Yes, you are right. In our case, the calling system never transports span information thus we always have to create a new span when @JmsListener method is called. It works for our case but I see that's not the general case. I have to think about a more generic way to solve both use cases.

**Comment by adriancole** [comment]
I think a future change would work a bit differently, creating a messaging span. Which version is this going for?

**Comment by marcingrzejszczak** [comment]
A more generic solution is related to this issue https://jira.spring.io/browse/SPR-14683. Until that one is fixed we can't do much about it. I'll close this one

**Pull request closed without merging**
