### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by ackintosh**
Obvious Fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ackintosh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=1157)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=1157) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ackintosh This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by marcingrzejszczak** [comment]
Can you fix it in the `docs` module, not the root `README`.

**Comment by ackintosh** [comment]
Thanks for pointing it out. I'll fix it.

**Comment by ackintosh** [comment]
@marcingrzejszczak  I've fixed it. Please have a look when you have time. 😌

**Comment by marcingrzejszczak** [comment]
Congrats @ackintosh on your first contribution!!

**Pull request merged**
