### PR TITLE
Add MilliSpan.getAnnotations()

### PR DESCRIPTION
**Pull request by rwinch**
This fixes the previous commit.

### CODE REVIEW

**Comment by spencergibb** [comment]
Since this uses lombok, you just need to change the name of the variable from `kVAnnotations` to `annotations`.

**Comment by rwinch** [comment]
@spencergibb Do you want to expose it as a setter too?

**Comment by spencergibb** [comment]
it's final, so it doesn't.  We currently don't need to.

**Comment by rwinch** [comment]
@spencergibb Thanks I didn't catch that. Will it also be immutable as documented on the interface?

**Comment by spencergibb** [comment]
That's probably the biggest inconsistency. One of the two needs to change :-) If that's the case, your change make a lot more sense.  We should also change `getTimelineAnnotations`.

**Comment by rwinch** [comment]
@spencergibb 

> One of the two needs to change :-)  

I'm fine with whichever you feel is best. I just wanted the project to build :)

> We should also change getTimelineAnnotations.

If it is ok with you, I'll leave this up to you since I'm not sure if you wanted to change the interface documentation or update the implementation.

**Pull request merged**
