### PR TITLE
TraceId spreading between containers thread pools fix

### PR DESCRIPTION
**Pull request by CyberpunkPerson**
The stack of calls was out of ThreadLocal, resulting in distorted reading by other threads under load

Fixes gh-2064

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Hi! Thanks for the PR. Can you add some tests to this please? We have similar code in the `ThreadLocalSpan` class, do you think that's buggy too?

**Comment by CyberpunkPerson** [comment]
Hi @marcingrzejszczak !
1. I checked `org.springframework.cloud.sleuth.ThreadLocalSpan` and yes, seems that it's also has this issue. 
2. I'll add some tests a little bit later. I used [Tracing](https://github.com/CyberpunkPerson/Tracing) sandbox to reproduce.

**Comment by marcingrzejszczak** [comment]
Hey @CyberpunkPerson , I took the liberty of fixing this and some other things in this commit https://github.com/spring-cloud/spring-cloud-sleuth/commit/66c63a53ff902f5d9c1d65595bec778389e044bd

**Comment by CyberpunkPerson** [comment]
**Note (for those who may faced with it):** 
If you want to have `traceId` per message you need to override default behavior, 
switch `singleRootSpanOnReceiveBatch` by

```
 @Bean
    KafkaTracing kafkaTracing(MessagingTracing messagingTracing, SleuthMessagingProperties properties) {
        return KafkaTracing.newBuilder(messagingTracing)
                .remoteServiceName(properties.getKafka().getRemoteServiceName())
                .singleRootSpanOnReceiveBatch(false)
                .build();
    }
```

otherwise `TracingConsumer` will reuse `traceId` for topic.

**Pull request closed without merging**
