### PR TITLE
Port SpanTag fix to 1.3.x

### PR DESCRIPTION
**Pull request by ethanbishop**
Fixes gh-990

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ethanbishop Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=1119)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=1119) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ethanbishop Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=1119)!

**Comment by marcingrzejszczak** [comment]
Congrats @ethanbishop on your first contribution !!! :)

**Comment by ethanbishop** [comment]
Thanks, hopefully the next will be more interesting!

**Pull request merged**
