### PR TITLE
GH-1319: Populate originalMessage when reconstructing ErrorMessage

### LINKED ISSUE #1319: TracingChannelInterceptor should copy over original message when reconstructing ErrorMessage
Currently, the way `TracingChannelInterceptor` constructs output message, original message is lost when dealing with `ErrorMessage`s.

This causes issues for consumers listening on SI's error channel and expecting the `originalMessage` field on the `ErrorMessage` to be populated.

### PR DESCRIPTION
**Pull request by Walliee**
fixes #1319

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Hey, thanks for the PR @Walliee . Could you please write a test that asserts the new behaviour?

**Comment by Walliee** [comment]
@marcingrzejszczak I added a test, please take a look.

**Comment by marcingrzejszczak** [comment]
Thanks @Walliee for the pull request!

**Comment by Walliee** [comment]
Hey @marcingrzejszczak, any chance this can be added to the 2.1.2.RELEASE milestone?

**Pull request merged**
