### PR TITLE
 Ensure that exception is handle only if there is a cycle on sleuthSkipPatternProvider

### PR DESCRIPTION
**Pull request by oburgosm**
Relates to #1679

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@oburgosm Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-sleuth&pullRequestId=1734)!

**Comment by marcingrzejszczak** [comment]
Can we have a test for that please?

**Comment by oburgosm** [comment]
Not enough with existing test `EndpointWithCyclicDependenciesTests`?

**Comment by marcingrzejszczak** [comment]
I mean we changed production code, no tests needed to be changed or added and the code still works. So how can we know that the new feature works fine?

**Pull request closed without merging**
