### PR TITLE
Optional/Null parameter used within @SpanTag

### PR DESCRIPTION
**Pull request by bedla**
Hi,
I found that when I have request parameter that is optional (`null` when controller method invoked) with combination with `@SpanTag`, tag is handled incorrectly.
I have created PR that solves it. Please look at tests to see usecases (see `NullParameterController`).
What do you think?
Thx,
Ivos

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Lgtm can you apply this against 2.3.x branch?

**Comment by marcingrzejszczak** [comment]
Hey @bedla , could you please apply this PR against 2.2.x branch?

**Comment by bedla** [comment]
No problem, you mean both branches?
(I am currently at vacations)

Dne po 29. 6. 2020 15:15 uživatel Marcin Grzejszczak <
notifications@github.com> napsal:

**Comment by marcingrzejszczak** [comment]
Ah I didn't know you're on holidays. I've merged your code to master and backported it to 2.2.x branch. Great work and enjoy your holidays :)

**Comment by bedla** [comment]
i am back :) thx for merge and sorry for inconvenience.

**Pull request merged**
