### PR TITLE
Updating readme: use Java 8 instead of 7

### PR DESCRIPTION
**Pull request by jonatan-ivanov**
The pom says 1.8, I guess this is outdated.

### CODE REVIEW

**Comment by spencergibb** [comment]
```
////
DO NOT EDIT THIS FILE. IT WAS GENERATED.
Manual changes to this file will be lost when it is generated again.
Edit the files in the src/main/asciidoc/ directory instead.
////
```

**Review by spencergibb — CHANGES_REQUESTED** [review]
this is an auto generated file

**Comment by marcingrzejszczak** [comment]
This is the file that should be fixed - https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/building.adoc

**Comment by jonatan-ivanov** [comment]
🤦🏼 
https://github.com/spring-cloud/spring-cloud-build/pull/208

**Pull request closed without merging**
