### PR TITLE
Makes message serializable

### LINKED ISSUE #520: TraceChannelInterceptor makes Message NonSerializable
The code:
```
MessageHeaderAccessor headers = MessageHeaderAccessor.getMutableAccessor(message);
headers.copyHeaders(messageBuilder.build().getHeaders());
return new GenericMessage<Object>(message.getPayload(), headers.getMessageHeaders());
```
returns the `GenericMessage` with the `MutableMessageHeaders` which has a reference to the outer `MessageHeaderAccessor` instance which isn't `Serializable`.

Would be better to use `MessageHeaderAccessor.toMessageHeaders()`. At least for now.
Although it clashes with the fix for #276...

For more info: https://jira.spring.io/browse/SPR-15262

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
without this change exceptions where thrown due to the fact that we were using a wrong method to retrieve headers
with this change that's changed

fixes #520

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
cc @dsyer I had to remove a test that checks for mutability of headers but as far as I understand @artembilan stuff was fixed in Spring Framework and we no longer need to have that mutability? We will not introduce regression with this change (https://github.com/spring-cloud/spring-cloud-sleuth/issues/276) ? The only test that we had for that issue is the one that I'm removing so I'd really prefer to have some new tests (but currently I'd need support how to write one)

**Comment by artembilan** [comment]
See https://jira.spring.io/browse/SPR-15262. So, you should place a message to your interceptor and perform that serialization hacks.

**Comment by marcingrzejszczak** [comment]
@dsyer @artembilan this will fail due to this test failing

```


	@Test
	public void nonExportableSpanCreation() {
		this.tracedChannel.send(MessageBuilder.withPayload("hi")
				.setHeader(TraceMessageHeaders.SAMPLED_NAME, Span.SPAN_NOT_SAMPLED).build());
		assertNotNull("message was null", this.message);

		String spanId = this.message.getHeaders().get(TraceMessageHeaders.SPAN_ID_NAME, String.class);
		then(spanId).isNotNull();
		then(TestSpanContextHolder.getCurrentSpan()).isNull();
		then(this.span.isExportable()).isFalse();
	}
```

Should remove this test due to the fact it got fixed somewhere? I didn't get the outcome of the discussions on Jira with whether it got fixed or not in Spring Core.

**Comment by marcingrzejszczak** [comment]
Ah yeah true. Check this commit - https://github.com/spring-cloud/spring-cloud-sleuth/pull/521/commits/85ba1904cadcb5b6f1c1fc985bff7e51e4c509a8 . Over there I made the span serializable and the added test passes but the `nonExportableSpanCreation` doesn't . With the current changes the `messageHeadersStillMutable` passes but the `nonExportableSpanCreation` doesn't. So the only wayis  to do the change from the commit and remove `messageHeadersStillMutable`. But it means that the headers are not mutable.

**Comment by artembilan** [comment]
@marcingrzejszczak , @dsyer , would you mind taking a look into your release plans on the matter?

Look, SF JIRA https://jira.spring.io/browse/SPR-15262 is for `4.3.7`, and its plan is Fabruary 28.

My idea to revert the change you did in the `TraceChannelInterceptor` and rely on the fact that it is fixed in the SF its own way. That serialization test will pass any way. Plus your `messageHeadersStillMutable` should work as well.

WDYT?

**Comment by marcingrzejszczak** [comment]
So you say that I should return to the `getHeaders()` and it will work OOB? Sounds perfect for me.

**Comment by artembilan** [comment]
Yes, ` headers.getMessageHeaders()` will work, but with the latest SF `4.3.7`. Right now only in `BUILD-SNAPSHOT`

**Comment by marcingrzejszczak** [comment]
Hmm but we take the version from Boot so we'd need to have the version updated from Boot and get the new Boot version. Or change the SF version only for Sleuth. WDYT @dsyer ?

**Comment by artembilan** [comment]
Spring Boot `1.5.2` is planned for March 2d.
Now everything depends of your release plans.

I think there is simple workaround like:

```
public class ImmutableMessageInterceptor extends ChannelInterceptorAdapter {

	@Override
	public Message<?> preSend(Message<?> message, MessageChannel channel) {
		MessageHeaderAccessor headers = MessageHeaderAccessor.getMutableAccessor(message);
		return  new GenericMessage<Object>(message.getPayload(), headers.toMessageHeaders());
	}

}
```
And we have to place this interceptor just after `TraceChannelInterceptor`.

So, this your fix (actually just a new serialization test) may really wait until the proper Spring Boot version.

**Comment by artembilan** [comment]
@marcingrzejszczak ,

Here you can find the workaround we have talked about: https://github.com/artembilan/spring-cloud-sleuth/commit/91e9b801b6fb205314f2dcdecf9adb19f571f486

I guess you can pull my commit to your PR.
Or... I can just apply it locally and merge! 😄

**Comment by marcingrzejszczak** [comment]
Done via 7caf522

**Pull request closed without merging**
