### PR TITLE
Getting header value case insensitive way

### PR DESCRIPTION
**Pull request by artemptushkin**
#1874 Make message header getter case insensitive for propagated headers

@marcingrzejszczak should we update native headers logic also? Seems like these are only _b3_, but but sure

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Yeah that's a good idea to check the native ones too.

**Comment by artemptushkin** [comment]
Okay, will be updated then

**Review by marcingrzejszczak — APPROVED** [review]

**Comment by marcingrzejszczak** [comment]
Thanks @artemptushkin ! You've managed to do the change just in time for the release :)

**Comment by artemptushkin** [comment]
@marcingrzejszczak nice, thanks :)

**Pull request merged**
